---
title: "Rmarkdown Generico"
output: pdf_document
date: "2024-05-06"
---
**Exercício 1**. Considere uma economia com o tempo discreto e infinito, i.e, t = 0, 1, 2... Nesta economia vivem duas pessoas de vida eterna indexadas por i = 1, 2. Existe um único bem, que é perecível, e cada pessoa tem uma dotação $e_t^i=1$ para todo $t$ deste bem. As preferências das pessoas sobre um fluxo de consumo $\left\{ c_t^i \right\}_{t=0}^{\infty}$ são dadas por:

$$u^i\left( \left\{ c_t^i \right\}_{t=0}^{\infty} \right) = \sum_{t=0}^{\infty} (\beta_{i})^t\ln {c_t^i,}$$
em que $0<\beta_1<\beta_2<1$. Toda informação desta economia é pública e não há nenhum risco. Em $t=0$, antes de receber a dotação, as pessoas se encontram em um mercado central e transacionam unidades do bem de consumo para todos os períodos. Denote por $p_t$ o preço de uma unidade do bem no período $t$. Em todo $t \geq 1$ as pessoas voltam ao mercado central para executar as trocas negociadas em $t=0$. Assuma que os acordos no início dos tempos são sempre honrados pelas pessoas.

(a) Defina uma alocação factível para esta economia.
